version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tbilisi
    open-pull-requests-limit: 3
    labels:
      - "type: dependencies"
      - "status: needs-triage"
    commit-message:
      prefix: chore(deps)
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: react-native
    groups:
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Tbilisi
    open-pull-requests-limit: 3
    labels:
      - "type: dependencies"
      - "area: release"
      - "status: needs-triage"
    commit-message:
      prefix: chore(deps)
    groups:
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
